### ISSUE TITLE
ERROR: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by mcianfrocco** [rocketmlhq/rmldnn#2]
Hello - I'm trying to run rmldnn on the following system. See command & error below.

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
$ nvidia-smi
Fri Apr 22 10:12:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          Off  | 00000000:3B:00.0 Off |                    0 |
|  0%   38C    P0    73W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          Off  | 00000000:5E:00.0 Off |                    0 |
|  0%   38C    P0    77W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A40          Off  | 00000000:AF:00.0 Off |                    0 |
|  0%   36C    P0    77W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A40          Off  | 00000000:D8:00.0 Off |                    0 |
|  0%   36C    P0    74W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```
Command:  singularity exec --nv ../software/rmldnn.sif mpirun -np 2 -x CUDA_VISIBLE_DEVICES=0,1 rmldnn --config= ./config_inpaint_feature_extraction.json

Error: [2022-Apr-21 22:33:00.365008] *** CUDA available! Will train on GPU ***
[2022-Apr-21 22:33:00.365016] ---------------------------------------------
[2022-Apr-21 22:33:00.477420] ERROR: CUDA error: no kernel image is available for execution on the device
Exception raised from launch_vectorized_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:119 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f1eaff9a569 in /usr/local/libtorch/1.7.0/lib/libc10.so)
frame #1: void at::native::gpu_kernel_impl<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::fill_kernel_cuda, 4u>, float (), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::fill_kernel_cuda, 4u>, float (), float> const&) + 0x862 (0x7f1e6127bf82 in /usr/local/libtorch/1.7.0/lib/libtorch_cuda.so)
```

**Comment by mcianfrocco** [comment]
`Does removing --nv flag help?`

Yes! the command is able to start successfully after removing the --nv flag with the following command: 

`$ singularity exec ../software/rmldnn.sif mpirun -np 2 -x CUDA_VISIBLE_DEVICES=0,1 rmldnn --config= ./config_inpaint_feature_extraction.json  `

**Comment by ssbotelh** [comment]
Hi Michael, thanks for the info above.
Removing the `--nv` flag is not really a solution, as it simply disables the GPU (the command worked because it ran on the CPUs). I only asked you to test it to make sure the issue was in fact with the GPU. I'm reopening the issue and we'll investigate. Thanks!

**Comment by ssbotelh** [comment]
Hi Michael,
Could you please try setting this environment variable before running the rmldnn command:
```
export CUDA_FORCE_PTX_JIT=1
singularity exec --nv ${RMLDNN_IMAGE} rmldnn --config= ./config_inpaint_feature_extraction.json
```

If this doesn't work, could you please try the following:
```
singularity exec --nv --env CUDA_FORCE_PTX_JIT=1 ${RMLDNN_IMAGE} rmldnn --config= ./config_inpaint_feature_extraction.json
```

Let me know if this changes anything. If it runs, please check the output for this message:
```
*** CUDA available! Will train on GPU ***
```

Thank you!

**Comment by mcianfrocco** [comment]
Thank you Sergio - I tried both approaches and got the following error: 

[2022-Apr-24 16:19:45.586579] ---------------------------------------------
[2022-Apr-24 16:19:45.586596] *** CUDA available! Will train on GPU ***
[2022-Apr-24 16:19:45.586604] ---------------------------------------------
[2022-Apr-24 16:19:45.690684] ERROR: CUDA error: no kernel image is available for execution on the device
Exception raised from launch_vectorized_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:119 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fba07266569 in /usr/local/libtorch/1.7.0/lib/libc10.so)
frame #1: void at::native::gpu_kernel_impl<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::fill_kernel_cuda, 4u>, float (), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::fill_kernel_cuda, 4u>, float (), float> const&) + 0x862 (0x7fb9b8547f82 in /usr/local/libtorch/1.7.0/lib/libtorch_cuda.so)
frame #2: void at::native::gpu_kernel<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::fill_kernel_cuda, 4u>, float (), float> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::fill_kernel_cuda, 4u>, float (), float> const&) + 0x16d (0x7fb9b854975d in /usr/local/libtorch/1.7.0/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x1fcd640 (0x7fb9b853a640 in /usr/local/libtorch/1.7.0/lib/libtorch_cuda.so)
frame #4: at::native::fill_kernel_cuda(at::TensorIterator&, c10::Scalar) + 0x2a (0x7fb9b853ba2a in /usr/local/libtorch/1.7.0/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdb25e5 (0x7fb9f33735e5 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x159677c (0x7fb9f3b5777c in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x1362c1d (0x7fb9f3923c1d in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #8: at::Tensor& c10::Dispatcher::callWithDispatchKey<at::Tensor&, at::Tensor&, c10::Scalar>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, c10::Scalar)> const&, c10::DispatchKey, at::Tensor&, c10::Scalar) const + 0x242 (0x7fb9f3a97172 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #9: at::Tensor::fill_(c10::Scalar) const + 0xee (0x7fb9f3c1f2de in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #10: at::native::constant_pad_nd(at::Tensor const&, c10::ArrayRef<long>, c10::Scalar) + 0xbf8 (0x7fb9f32d8ef8 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x1591e38 (0x7fb9f3b52e38 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x15e9dd8 (0x7fb9f3baadd8 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x14e12d6 (0x7fb9f3aa22d6 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #14: at::constant_pad_nd(at::Tensor const&, c10::ArrayRef<long>, c10::Scalar) + 0x14d (0x7fb9f39acd9d in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x2a3f237 (0x7fb9f5000237 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x15e9dd8 (0x7fb9f3baadd8 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x14e12d6 (0x7fb9f3aa22d6 in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #18: at::constant_pad_nd(at::Tensor const&, c10::ArrayRef<long>, c10::Scalar) + 0x14d (0x7fb9f39acd9d in /usr/local/libtorch/1.7.0/lib/libtorch_cpu.so)
frame #19: <unknown function> + 0xd216f (0x55cdbcf5116f in rmldnn)
frame #20: <unknown function> + 0xd36f0 (0x55cdbcf526f0 in rmldnn)
frame #21: <unknown function> + 0xbf501 (0x55cdbcf3e501 in rmldnn)
frame #22: <unknown function> + 0xe1081 (0x55cdbcf60081 in rmldnn)
frame #23: <unknown function> + 0x1469ce (0x55cdbcfc59ce in rmldnn)
frame #24: <unknown function> + 0x179967 (0x55cdbcff8967 in rmldnn)
frame #25: <unknown function> + 0x923ee (0x55cdbcf113ee in rmldnn)
frame #26: <unknown function> + 0x4d159 (0x55cdbcecc159 in rmldnn)
frame #27: __libc_start_main + 0xe7 (0x7fb9b4cf1bf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #28: <unknown function> + 0x4db7a (0x55cdbceccb7a in rmldnn)

**Comment by mcianfrocco** [comment]
Hi Sergio - as a follow-up, I'm also unable to run these commands on GTX2080Ti GPUs.

**Comment by ssbotelh** [comment]
Hi Michael, thanks for the feedback. Do you get the same error message on the GTX? Also, could you please let me know the following for the GTX:

1. OS type and version
2. nvidia-smi output

Thanks again!

**Comment by mcianfrocco** [comment]
Hi Sergio - after running a few more tests on the GTX2080Ti, I realized the issue was how I was submitting it to my cluster, not rmldnn. 

Now, the job is running on GTX2080Ti without issue on multiple GPUs. Perhaps the error above is related to the A40 GPUs. 

Command: 
`singularity exec --nv rmldnn.sif mpirun -np 4 -x CUDA_VISIBLE_DEVICES=0,1,2,3 rmldnn --config=./config_inpaint_feature_extraction.json > rmldnn.out 2> rmldnn.err`

For record-keeping: 

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
$ nvidia-smi
Mon Apr 25 13:01:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:3B:00.0 Off |                  N/A |
| 27%   43C    P2    61W / 250W |   3452MiB / 11264MiB |     22%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:5E:00.0 Off |                  N/A |
| 27%   42C    P2    76W / 250W |   3452MiB / 11264MiB |     20%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:86:00.0 Off |                  N/A |
| 27%   43C    P2    71W / 250W |   3452MiB / 11264MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:D8:00.0 Off |                  N/A |
| 26%   43C    P2    79W / 250W |   3452MiB / 11264MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     32091      C   rmldnn                           3449MiB |
|    1   N/A  N/A     32092      C   rmldnn                           3449MiB |
|    2   N/A  N/A     32093      C   rmldnn                           3449MiB |
|    3   N/A  N/A     32094      C   rmldnn                           3449MiB |
```

**Comment by mcianfrocco** [comment]
Hi Sergio - that commands does not return anything. Here is the content of the /usr/local directory: 

```
$ ls /usr/local/
bin  etc  games  include  lib  lib64  libexec  sbin  share  src
```

**Comment by ssbotelh** [comment]
Thanks. I was trying to see what version of CUDA you have on disk, but apparently RedHat keeps it at a different location. 
What does this command return?
```
nvcc --version
```

Thanks again.

**Comment by mcianfrocco** [comment]
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
```

**Comment by ssbotelh** [comment]
Hi Michael, 
The issue above was, in fact, due to lack of support for the A-series GPU architecture in certain libraries we use. Those have been updated, and I put out a new rmldnn image in DockerHub. Please try it out and let me know if it works on your A40 system:
```
sudo singularity build rmldnn.sif docker://rocketml/rmldnn:1.1_beta
```
Thank you.
